apiVersion: v1
kind: Pod
metadata:
  name: pod-sample
  labels:
    app: pod-sample
  namespace: tl-test
spec:
  containers:
    - name: pod-sample-container
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']